# Generated by Django 3.0.6 on 2020-05-05 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('img', models.ImageField(upload_to='Photos')),
                ('img_thumb', models.ImageField(upload_to='Photos/thumbnails')),
                ('instagram', models.URLField(default='https://www.instagram.com/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('profile_instagram', models.URLField(default='https://www.instagram.com/')),
                ('page_instagram', models.URLField(default='https://www.instagram.com/')),
                ('twitter', models.URLField(default='https://twitter.com')),
                ('facebook', models.URLField(default='https://www.facebook.com/')),
                ('email', models.URLField(default='https://www.google.com/')),
                ('profile_picture', models.ImageField(upload_to='Profile')),
                ('index_background', models.ImageField(upload_to='Profile')),
                ('profile_description', models.TextField()),
            ],
        ),
    ]
