# Generated by Django 3.0.6 on 2020-05-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='developer_website',
            field=models.URLField(default='https://www.google.com/'),
        ),
    ]
